CREATE TABLE `cmdb_vip` (
  `id` bigint NOT NULL COMMENT 'cmdb_id',
  `vip_port` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '虚拟IP与端口',
  `vip` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '虚拟服务ip',
  `vport` int DEFAULT NULL COMMENT '虚拟服务端口',
  `department` varchar(32) DEFAULT NULL COMMENT '所属部门',
  `cost` varchar(32) DEFAULT NULL COMMENT '成本事业部',
  `idc` varchar(32) DEFAULT NULL COMMENT '机房信息',
  `status` varchar(32) DEFAULT NULL COMMENT '状态（F5上的都是使用中的，云平台有使用中/未使用的）',
  `type` varchar(16) DEFAULT NULL COMMENT '类型 枚举值：内网 外网',
  `source` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '机房信息',
  `operator` varchar(32) DEFAULT NULL COMMENT '运营商',
  `env` varchar(16) DEFAULT NULL COMMENT '环境',
  `ip_type` varchar(16) DEFAULT NULL COMMENT '网络类型（ipv4/ipv6)',
  `protocol` varchar(16) DEFAULT NULL COMMENT '协议',
  `nat` varchar(16) DEFAULT NULL COMMENT '源地址转换',
  `load_balance` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '负载均衡算法',
  `get_client_ip` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '客户端IP (TCP/UDP_直连、TCP_SendProxy、HTTP_X-Forwarded-For)',
  `certificate` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '证书',
  `idle_timeout` varchar(16) DEFAULT NULL COMMENT '空闲超时时间',
  `access_control` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '访问控制',
  `deleted` int DEFAULT '0' COMMENT '是否删除 1 是 0 否',
  `drop_date` date DEFAULT NULL,
  `update_date` datetime DEFAULT NULL COMMENT '修改时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `isp` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '运营商  电信 移动 联通',
  PRIMARY KEY (`id`),
  KEY `cmdb_vip_vip_IDX` (`vip`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='cmdb虚拟ip'
